services:
  # Service Héros
  hero-service:
    build: ./services/hero
    container_name: hero-service
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  # Service Donjon
  dungeon-service:
    build: ./services/dungeon
    container_name: dungeon-service
    ports:
      - "5002:5002"

  # Service Combat
  fight-service:
    build: ./services/fight
    container_name: fight-service
    ports:
      - "5003:5003"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  # Client React
  client:
    build: ./client
    container_name: react-client
    ports:
      - "3000:80"

 # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port RabbitMQ
      - "15672:15672" # Interface de gestion RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest